registry:
  restart: always
  image: registry:2
  ports:
    - 443:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /cert/fullchain.pem
    REGISTRY_HTTP_TLS_KEY:         /cert/privkey.pem
  volumes:
    - /docker-registry/registry:/var/lib/registry
    - /docker-registry/cert/:/cert
    - /docker-registry/auth/:/auth
