apiVersion: v1
kind: Service
metadata:
  name: cluster-node
spec:
  selector:
    app: cluster
    component: node
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  - port: 33060
    targetPort: 33060
    name: mysqlx
---

apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql-node
  labels:
    app: cluster
    component: node
spec:
  serviceName: "cluster-node"
  replicas: 3
  selector:
    matchLabels:
      app: cluster
      component: node
  template:
    metadata:
      labels:
        app: cluster
        component: node
    spec:
      containers:
      - name: node
        image: k8s-docker.k8s.local/mysql-node
        env:
        - name: MYSQL_CLUSTER_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: cluster-environment
              key: MYSQL_CLUSTER_ADMIN_USERNAME
        - name: MYSQL_CLUSTER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-environment
              key: MYSQL_CLUSTER_ADMIN_PASSWORD
        resources:
          limits:
            memory: "1Gi"
            cpu: "100m"

