apiVersion: v1
kind: Service
metadata:
  name: "cluster-router"
spec:
  selector:
    app: cluster
    component: router
  ports:
  - port: 6446
    targetPort: 6446
    name: mysql
  - port: 64460
    targetPort: 64460
    name: mysqlx
---

apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql-router
  labels:
    app: cluster
    component: router
spec:
  serviceName: "cluster-router"
  replicas: 1
  selector:
    matchLabels:
      app: cluster
      component: router
  template:
    metadata:
      labels:
        app: cluster
        component: router
    spec:
      containers:
      - name: router
        image: k8s-docker.k8s.local/mysql-router
        env:
        - name: MYSQL_CLUSTER_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: cluster-environment
              key: MYSQL_CLUSTER_ADMIN_USERNAME
        - name: MYSQL_CLUSTER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-environment
              key: MYSQL_CLUSTER_ADMIN_PASSWORD
        resources:
          limits:
            memory: "1Gi"
            cpu: "100m"
