---
# tasks file for k8s-install

- name: Add repository
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Change SElinux mode
  selinux:
    state: disabled

- name: Disable swap
  command: swapoff -a

# Disable swap
- name: Remove swapfile from /etc/fstab
  raw: "sed -i 's/\\(^\\)\\(.*swap.*\\)/#&1/' /etc/fstab "

# Prepare host
## Modify sysctl
- name: copy k8s.conf
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: reload sysctl and load module
  raw: "{{ item }}"
  with_items:
    - "modprobe br_netfilter"
    - "sysctl -p /etc/sysctl.d/k8s.conf"

# Install service
- name: Install packages
  yum:
     name: ['kubelet','kubeadm','kubectl']
     disable_excludes: kubernetes
     state: latest

- name: Starting kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
